CREATE TABLE `ads` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `description` tinytext NOT NULL,
  `price` decimal(10,2) NOT NULL,
  `phone` varchar(255) NOT NULL,
  `type` varchar(255) DEFAULT 'sell',
  `town_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `is_published` tinyint(1) NOT NULL DEFAULT '0',
  `is_deleted` tinyint(1) DEFAULT '0',
  `image_4` tinytext DEFAULT NULL,
  `image_3` tinytext DEFAULT NULL,
  `image_2` tinytext DEFAULT NULL,
  `image_1` tinytext DEFAULT NULL,
  `image_main` tinytext DEFAULT NULL,
  `category_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  KEY `fk_4` (`town_id`),
  KEY `fk_5` (`user_id`),
  KEY `fk_13` (`category_id`),
  CONSTRAINT `fk_10` FOREIGN KEY (`user_id`) REFERENCES `last_dance`.`users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_12` FOREIGN KEY (`town_id`) REFERENCES `last_dance`.`towns` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_14` FOREIGN KEY (`category_id`) REFERENCES `last_dance`.`categories` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=1;